/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Categories: typeof import('./components/Categories.vue')['default']
    ProductCard: typeof import('./components/ProductCard.vue')['default']
    ProductsByCategory: typeof import('./components/ProductsByCategory.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
